name: Test pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: checking file changes
        id: version-check
        run: |
          echo "checking files"

          CHANGEDFILES=$(git diff --name-only HEAD~1 HEAD)
          echo "changed files"
          echo "$CHANGEDFILES" 

      - name: setup up node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x' 
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Angular build
        run: npm run build -- --configuration production
      